redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\User\\noya-repo"
publishOrigin = "config"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/"
to = "/design-a.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]